<?php
/**
 * InlineResponse2001Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * REST API Documentation
 *
 * Can not resolve Intro.md
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.18
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * InlineResponse2001Test Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse2001
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse2001Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse2001"
     */
    public function testInlineResponse2001()
    {
    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {
    }

    /**
     * Test attribute "pattern"
     */
    public function testPropertyPattern()
    {
    }

    /**
     * Test attribute "valid"
     */
    public function testPropertyValid()
    {
    }

    /**
     * Test attribute "box"
     */
    public function testPropertyBox()
    {
    }

    /**
     * Test attribute "rural"
     */
    public function testPropertyRural()
    {
    }

    /**
     * Test attribute "customer"
     */
    public function testPropertyCustomer()
    {
    }
}
