<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * REST API Documentation
 *
 * Can not resolve Intro.md
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.18
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for dELETEAgentsId
     *
     * .
     *
     */
    public function testDELETEAgentsId()
    {
    }

    /**
     * Test case for dELETEConsolidatedShipmentsConsolidatedId
     *
     * .
     *
     */
    public function testDELETEConsolidatedShipmentsConsolidatedId()
    {
    }

    /**
     * Test case for dELETEConsolidatedShipmentsConsolidatedIdParcelPartOrderNo
     *
     * .
     *
     */
    public function testDELETEConsolidatedShipmentsConsolidatedIdParcelPartOrderNo()
    {
    }

    /**
     * Test case for dELETEPreparedShipmentsPrepareId
     *
     * .
     *
     */
    public function testDELETEPreparedShipmentsPrepareId()
    {
    }

    /**
     * Test case for dELETEShipmentsShipmentId
     *
     * .
     *
     */
    public function testDELETEShipmentsShipmentId()
    {
    }

    /**
     * Test case for dELETEStoredShipmentsStoredId
     *
     * .
     *
     */
    public function testDELETEStoredShipmentsStoredId()
    {
    }

    /**
     * Test case for gETAddressesAgents
     *
     * .
     *
     */
    public function testGETAddressesAgents()
    {
    }

    /**
     * Test case for gETAddressesZipcodes
     *
     * .
     *
     */
    public function testGETAddressesZipcodes()
    {
    }

    /**
     * Test case for gETAlerts
     *
     * .
     *
     */
    public function testGETAlerts()
    {
    }

    /**
     * Test case for gETConsolidatedShipments
     *
     * .
     *
     */
    public function testGETConsolidatedShipments()
    {
    }

    /**
     * Test case for gETConsolidatedShipmentsConsolidatedIdPdfs
     *
     * .
     *
     */
    public function testGETConsolidatedShipmentsConsolidatedIdPdfs()
    {
    }

    /**
     * Test case for gETConsolidatedShipmentsConsolidatedIdPdfsPdfId
     *
     * .
     *
     */
    public function testGETConsolidatedShipmentsConsolidatedIdPdfsPdfId()
    {
    }

    /**
     * Test case for gETConsolidatedShipmentsConsolidatedIdPrints
     *
     * .
     *
     */
    public function testGETConsolidatedShipmentsConsolidatedIdPrints()
    {
    }

    /**
     * Test case for gETConsolidatedShipmentsConsolidatedIdPrintsPrintId
     *
     * .
     *
     */
    public function testGETConsolidatedShipmentsConsolidatedIdPrintsPrintId()
    {
    }

    /**
     * Test case for gETDeliveryCheckoutsDeliveryCheckoutId
     *
     * .
     *
     */
    public function testGETDeliveryCheckoutsDeliveryCheckoutId()
    {
    }

    /**
     * Test case for gETMetaListsPartners
     *
     * .
     *
     */
    public function testGETMetaListsPartners()
    {
    }

    /**
     * Test case for gETOnboardingAccounts
     *
     * .
     *
     */
    public function testGETOnboardingAccounts()
    {
    }

    /**
     * Test case for gETOnboardingApplicationsLanguage
     *
     * .
     *
     */
    public function testGETOnboardingApplicationsLanguage()
    {
    }

    /**
     * Test case for gETOnboardingTermsLanguage
     *
     * .
     *
     */
    public function testGETOnboardingTermsLanguage()
    {
    }

    /**
     * Test case for gETPreparedShipmentsPrepareId
     *
     * .
     *
     */
    public function testGETPreparedShipmentsPrepareId()
    {
    }

    /**
     * Test case for gETShipments
     *
     * .
     *
     */
    public function testGETShipments()
    {
    }

    /**
     * Test case for gETShipmentsShipmentIdPdfs
     *
     * .
     *
     */
    public function testGETShipmentsShipmentIdPdfs()
    {
    }

    /**
     * Test case for gETShipmentsShipmentIdPdfsPdfId
     *
     * .
     *
     */
    public function testGETShipmentsShipmentIdPdfsPdfId()
    {
    }

    /**
     * Test case for gETShipmentsShipmentIdPrints
     *
     * .
     *
     */
    public function testGETShipmentsShipmentIdPrints()
    {
    }

    /**
     * Test case for gETShipmentsShipmentIdPrintsPrintId
     *
     * .
     *
     */
    public function testGETShipmentsShipmentIdPrintsPrintId()
    {
    }

    /**
     * Test case for gETStoredShipments
     *
     * .
     *
     */
    public function testGETStoredShipments()
    {
    }

    /**
     * Test case for pOSTAgents
     *
     * .
     *
     */
    public function testPOSTAgents()
    {
    }

    /**
     * Test case for pOSTAgentsId
     *
     * .
     *
     */
    public function testPOSTAgentsId()
    {
    }

    /**
     * Test case for pOSTConsolidatedShipments
     *
     * .
     *
     */
    public function testPOSTConsolidatedShipments()
    {
    }

    /**
     * Test case for pOSTConsolidatedShipmentsConsolidatedIdShipments
     *
     * .
     *
     */
    public function testPOSTConsolidatedShipmentsConsolidatedIdShipments()
    {
    }

    /**
     * Test case for pOSTConsolidatedShipmentsConsolidatedIdShipmentsManifest
     *
     * .
     *
     */
    public function testPOSTConsolidatedShipmentsConsolidatedIdShipmentsManifest()
    {
    }

    /**
     * Test case for pOSTDeliveryCheckoutsDeliveryCheckoutId
     *
     * .
     *
     */
    public function testPOSTDeliveryCheckoutsDeliveryCheckoutId()
    {
    }

    /**
     * Test case for pOSTDeliveryCheckoutsDeliveryCheckoutIdSummaryCurrency
     *
     * .
     *
     */
    public function testPOSTDeliveryCheckoutsDeliveryCheckoutIdSummaryCurrency()
    {
    }

    /**
     * Test case for pOSTOnboardingApplicationsApplicationCode
     *
     * .
     *
     */
    public function testPOSTOnboardingApplicationsApplicationCode()
    {
    }

    /**
     * Test case for pOSTPreparedShipmentsPrepareId
     *
     * .
     *
     */
    public function testPOSTPreparedShipmentsPrepareId()
    {
    }

    /**
     * Test case for pOSTPreparedShipmentsPrepareIdShipments
     *
     * .
     *
     */
    public function testPOSTPreparedShipmentsPrepareIdShipments()
    {
    }

    /**
     * Test case for pOSTPreparedShipmentsPrepareIdStoredShipments
     *
     * .
     *
     */
    public function testPOSTPreparedShipmentsPrepareIdStoredShipments()
    {
    }

    /**
     * Test case for pOSTPrices
     *
     * .
     *
     */
    public function testPOSTPrices()
    {
    }

    /**
     * Test case for pOSTPricesHistory
     *
     * .
     *
     */
    public function testPOSTPricesHistory()
    {
    }

    /**
     * Test case for pOSTShipments
     *
     * .
     *
     */
    public function testPOSTShipments()
    {
    }

    /**
     * Test case for pOSTStoredShipments
     *
     * .
     *
     */
    public function testPOSTStoredShipments()
    {
    }

    /**
     * Test case for pOSTStoredShipmentsStoredIdShipments
     *
     * .
     *
     */
    public function testPOSTStoredShipmentsStoredIdShipments()
    {
    }
}
